disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - force_cast
  - type_body_length
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ./build/SourcePackages/checkouts/swift-argument-parser/*
