#!/bin/zsh

#  Postinstall script for outset CLI
#
#  Created by Bart Reardon on 9/1/2023.
#

APP_PATH="/usr/local/outset/Outset.app"

# register the app bundle
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister "${APP_PATH}"

# run boot argument - creates necessary paths and folders
"${APP_PATH}/Contents/MacOS/Outset" --boot

## LaunchDaemons
LD_ROOT="/Library/LaunchDaemons"
DAEMONS=(
  "${LD_ROOT}/io.macadmins.outset.boot.plist"
  "${LD_ROOT}/io.macadmins.outset.cleanup.plist"
  "${LD_ROOT}/io.macadmins.outset.login-privileged.plist"
)

## LaunchAgents
LA_ROOT="/Library/LaunchAgents"
AGENTS=(
  "${LA_ROOT}/io.macadmins.outset.login.plist"
  "${LA_ROOT}/io.macadmins.outset.on-demand.plist"
  "${LA_ROOT}/io.macadmins.outset.login-window"
)

for daemon in ${DAEMONS}; do
    if [ -e "${daemon}" ]; then
        /bin/launchctl bootstrap system "${daemon}"
    fi
done

for agent in ${AGENTS}; do
    echo ${agent}
done
