#!/bin/bash
#==================================================================================
#
#          FILE: outset-pkg
#
#         USAGE: ./outset-pkg -a | --file [--target] | [--version] | [--build-path]
#
#   DESCRIPTION: Creates a PKG of /usr/local/outset processing directories 
#                Either for one file or package the entire structure 
#
#         NOTES: ---
#        AUTHOR: Bart Reardon
#  ORGANIZATION: Macadmins Open Source
#       CREATED: 2023-03-23
#      REVISION: 1.0
#
#       COPYRIGHT: (C) Macadmins Open Source 2023. All rights reserved.
#
#==================================================================================

FILE_TO_PACKAGE=""
FILE_TARGET="login-once"
BUILD_ALL=false
BUILD_DIRECTORY="/var/tmp/outset"

PKGTITLE="Outset Custom Content"
PKGVERSION="1.0"
PKGID="io.macadmins.Outset.custom-content"

OUTSET_ROOT="/usr/local/outset"
PGKROOT="${BUILD_DIRECTORY}/PGKROOT"
PKGNAME="outset-custom-content_v${PKGVERSION}"

printUsage() {
    echo "USAGE: ${0##*/} -a | --file [--target] | [--version] | [--build-path]"
    echo "    -a                     package all scripts into one package"
    echo "    --file <filename>      package the selected file"
    echo "    --target <directory>   file target directory (default 'login-once')"
    echo "    --version <number>     set package version to the selected number (default is '1.0')"
    echo "    --build-path <path>    path to use as the build location (default ${BUILD_DIRECTORY})" 
    echo "    --help                 print this message"
}

validateVersion() {
    # Regular expression to match a version number
    regex='^[0-9]+([.][0-9]+)*$'

    # Check if the string matches the regular expression
    if [[ $1 =~ $regex ]]; then
        echo $1
    else
        return 1
    fi
}

validateTarget() {
    targetList=($(ls -d ${OUTSET_ROOT}/login-* ${OUTSET_ROOT}/boot-* ${OUTSET_ROOT}/on-*))
    for target in "${targetList[@]}"; do
        if [[ "${target##*/}" == "$1" ]]; then
            echo "${target##*/}"
            return 0
        fi
    done
    return 1
}

printValidTargets() {
    targetList=($(ls -d ${OUTSET_ROOT}/login-* ${OUTSET_ROOT}/boot-* ${OUTSET_ROOT}/on-*))
    echo "Invalid target name '$1'"
    echo "Valid targets:"
    for target in ${targetList[@]}; do
        echo "  [${target##*/}]"
    done
    exit 1
}

exitWithError() {
    echo "$1"
    exit 1
}

# if no arguments passed, print help and exit
if [[ "$#" -eq 0 ]]; then
    printUsage
    exit 0
fi

# Loop through named arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --file) FILE_TO_PACKAGE="$2"; shift ;;
        --target) FILE_TARGET=$(validateTarget "$2") || printValidTargets "$2"; shift ;;
        --version) PKGVERSION=$(validateVersion "$2") || exitWithError "invalid version number $2"; shift ;;
        --build-path)
            if [[ -e "$2" ]]; then 
                BUILD_DIRECTORY="${2%/}"
                PGKROOT="${BUILD_DIRECTORY}/PGKROOT"
            else
                exitWithError "path '$2' not found"
            fi
            shift
        ;;
        --help|help) printUsage; exit 0 ;;
        -a) BUILD_ALL=true ;;
        *) echo "Unknown parameter passed: $1"; printUsage; exit 1 ;;
    esac
    shift
done

if [[ -n $FILE_TO_PACKAGE ]]; then
    PKGID="io.macadmins.Outset.${FILE_TARGET}-${FILE_TO_PACKAGE##*/}"
    PKGNAME="outset-${FILE_TARGET}-${FILE_TO_PACKAGE##*/}_v${PKGVERSION}"
else
    PKGNAME="outset-custom-content_v${PKGVERSION}"
fi

if $BUILD_ALL; then
    echo "making all the things"
fi

# create PGKROOT structure
mkdir -p "${PGKROOT}${OUTSET_ROOT}"
if [[ -n $FILE_TO_PACKAGE ]]; then 
    TARGET_DIR="${PGKROOT}${OUTSET_ROOT}/${FILE_TARGET}/"
    mkdir -p "${TARGET_DIR}"
    if [[ -e "${FILE_TO_PACKAGE}" ]]; then
        cp "${FILE_TO_PACKAGE}" "${TARGET_DIR}"
    else
        echo "${FILE_TO_PACKAGE} doesn't exist"
        exit 1
    fi
elif $BUILD_ALL; then
    for folder in $(ls -d ${OUTSET_ROOT}/login-* ${OUTSET_ROOT}/boot-* ${OUTSET_ROOT}/on-*); do
        cp -r "${folder}" "${PGKROOT}${OUTSET_ROOT}"
    done
fi

# create package
/usr/bin/pkgbuild --root "${PGKROOT}" --identifier ${PKGID} --version ${PKGVERSION} "${BUILD_DIRECTORY}/${PKGNAME}.component.pkg"
/usr/bin/productbuild --identifier ${PKGID} --package "${BUILD_DIRECTORY}/${PKGNAME}.component.pkg" "${BUILD_DIRECTORY}/${PKGNAME}.pkg"

# clean up
rm -r "${PGKROOT}"
rm "${BUILD_DIRECTORY}/${PKGNAME}.component.pkg"

# done
echo "Package has been created at ${BUILD_DIRECTORY}/${PKGNAME}.pkg"
